
version: '3.8'

services:
  # bookstore:
  #   container_name: p2p-book
  #   build:
  #     context: . # Adjust this path to your Next.js app's directory
  #     dockerfile: Dockerfile # Assuming you have a Dockerfile in your Next.js app directory
  #   volumes:
  #     - .:/usr/src/app # Mount the app directory into the container
  #     - /usr/src/app/node_modules # Keep node_modules on a named volume
  #   ports:
  #     - "3000:3000" # Expose port 3000 for the Next.js app
  #   environment:
  #     - DATABASE_URL=postgres://admin:admin1234@postgres:5432/bookstore # Adjust with your DB credentials
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres-db
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data between container restarts
      - ./prisma/init/vector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    environment:
      POSTGRES_DB: bookstore # Your database name
      POSTGRES_USER: admin # Your database user
      POSTGRES_PASSWORD: admin1234 # Your database password
    ports:
      - "5432:5432" # Expose PostgreSQL port
    

volumes:
  postgres_data: # Named volume for PostgreSQL
