import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { MainNav } from "@/components/nav"
import { Toaster } from "@/components/ui/toaster";
import { getUser } from "@/lib/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user = null;
  try {
  user = await getUser();
  } catch (error) {
    console.error(error)
      }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center  ">
            <MainNav user={user}/>
            {children}
            <Toaster />

          </main>

        </body>
      </html>
    </ClerkProvider>
  );
}
